### ISSUE TITLE
CentOS - ./falcon-linux-deploy.sh: line 38: python3: command not found

### ISSUE THREAD

**Issue by BeatKO** [CrowdStrike/falcon-linux-install-bash#1]
Trying to run this script in Centos and getting this error

`./falcon-linux-deploy.sh: line 38: python3: command not found`

python is installed on this server.

My 38 line : 
`    python3 -c "import sys, json; print(json.load(sys.stdin)['access_token'])")
`

**Comment by BeatKO** [comment]
Solved it.

**Comment by shawndwells** [comment]
@BeatKO if you'd be willing, could you comment on what the error and fix was? This could help us improve the documentation, sample commands, etc, so that others don't have to spend time troubleshooting if they encounter a similar problem.

**Comment by BeatKO** [comment]
The script downloading the latest version of the EDR Sensor agent.
And i tried to install it on my Centos 6/7, that's why it didn't work.
