### ISSUE TITLE
AWS SSM install broken on ubuntu

### ISSUE THREAD

**Issue by isimluk** [CrowdStrike/falcon-linux-install-bash#26]
AWS SSM disregards shebang and it will run the script using `/bin/dash` a minimalistic POSIX shell.

The `dash` support has been broken lately:
```
# dash falcon-linux-deploy.sh 
falcon-linux-deploy.sh: 89: falcon-linux-deploy.sh: Syntax error: "(" unexpected (expecting "}")
```

seems that `( )` bellow is bashism
```
    sensor_versions=( )
    for i in $sensor_update_versions; do
        sensor_versions+=("$i")
    done
```

**Comment by redhatrises** [comment]
Do we also need to add the following content as well https://github.com/CrowdStrike/Cloud-AWS/blob/main/Agent-Install-Examples/bash/API-download/install.sh#L165-L231 ?

**Comment by isimluk** [comment]
Oh, we don't support AWS SSM at all here. I guess the dash part is notabug then.

**Comment by redhatrises** [comment]
Reopening because this bug still exists actually regardless of AWS SSM. :D

**Comment by redhatrises** [comment]
#27 fixes the dash problem... but we should probably keep this open to address the SSM support problem.

**Comment by carlosmmatos** [comment]
So is the idea here to support `/bin/dash`?

**Comment by isimluk** [comment]
Yes, we need to support dash, but we should also perhaps include https://github.com/CrowdStrike/Cloud-AWS/blob/main/Agent-Install-Examples/bash/API-download/install.sh#L165-L231 at some point.

**Comment by redhatrises** [comment]
At this point, we need to add the SSM functionality from the AWS install.sh script to this script.
