### ISSUE TITLE
Allowing for N-2 and N-1 deployments

### ISSUE THREAD

**Issue by georgechp** [CrowdStrike/falcon-linux-install-bash#3]
This script pulls the latest sensor version, however most environments will run an N-1 or N-2 version on linux which means you're installing latest and then downgrading due to sensor update policies in the falcon console. Can the script be upgraded to accomodate this requirements?

**Comment by shawndwells** [comment]
The CrowdStrike sensor download API defaults to the latest version.

That said, believe either @redhatrises or @isimluk recently wrote some golang code around sensor download. How did y'all solve this?

**Comment by BaDxKaRMa** [comment]
I ran into this and I've been using the offset value in the filter to return an older version. So far through 3 sensor version updates, I haven't ran into an issue.
